/**
* AI STATEMENT
* This file was generated by AI, specifically Copilot, to provide us
* with an initial visualization for our web application. This is only our
* first iteration to prove that our implementation works visually. We intend 
* to refine and alter this file, slightly or entirely reworking it from its 
* current state.
*/

// Simple leaderboard renderer
// Loads JSON from sample_players.json by default or uses an uploaded file.

const statusEl = document.getElementById('status');
const tbody = document.querySelector('#leaderboard tbody');
const refreshBtn = document.getElementById('refreshBtn');

let currentPlayers = []; // store players fetched from backend

function setStatus(msg, isError = false) {
  statusEl.textContent = msg;
  statusEl.style.color = isError ? '#b91c1c' : '';
}

function computeWinRate(p) {
  const total = p.winRecord + p.lossRecord;
  return total === 0 ? 0 : p.winRecord / total;
}

function sortPlayers(players) {
  return players.sort((a, b) => {
    if (b.rating !== a.rating) return b.rating - a.rating;
    const wb = computeWinRate(b), wa = computeWinRate(a);
    if (wb !== wa) return wb - wa;
    if (b.winRecord !== a.winRecord) return b.winRecord - a.winRecord;
    if (a.lossRecord !== b.lossRecord) return a.lossRecord - b.lossRecord;
    return a.name.localeCompare(b.name);
  });
}

function render(players) {
  tbody.innerHTML = '';
  players.forEach((p, i) => {
    const tr = document.createElement('tr');

    tr.innerHTML = `
      <td class="rank">${i + 1}</td>
      <td class="name">${p.name}</td>
      <td>${p.rating.toFixed(0)}</td>
      <td>${p.winRecord}</td>
      <td>${p.lossRecord}</td>
      <td>${(computeWinRate(p) * 100).toFixed(1)}%</td>
    `;
    tbody.appendChild(tr);
  });
}

async function fetchPlayers() {
  try {
    const res = await fetch("/players");
    const players = await res.json();
    currentPlayers = players;
    render(sortPlayers(players));
    setStatus(`Loaded ${players.length} players.`);
  } catch (err) {
    console.error(err);
    setStatus('Failed to load players: ' + err.message, true);
  }
}

async function addPlayer() {
  const name = document.getElementById('newName').value.trim();
  const wins = Number(document.getElementById('newWins').value || 0);
  const losses = Number(document.getElementById('newLosses').value || 0);

  if (!name) {
    setStatus('Player must have a name.', true);
    return;
  }

  try {
    const res = await fetch("/add_player", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, wins, losses })
    });

    const newPlayer = await res.json();
    currentPlayers.push(newPlayer);
    render(sortPlayers(currentPlayers));
    setStatus(`Added player '${newPlayer.name}' with rating ${newPlayer.rating.toFixed(0)}`);
  } catch (err) {
    console.error(err);
    setStatus('Failed to add player: ' + err.message, true);
  }

  document.getElementById('newName').value = '';
  document.getElementById('newWins').value = '';
  document.getElementById('newLosses').value = '';
}

refreshBtn.addEventListener('click', fetchPlayers);
document.getElementById('addPlayerBtn').addEventListener('click', addPlayer);

// In script.js

// --- New Function ---
async function updatePlayer() {
    const name = document.getElementById('updateName').value.trim();
    const wins = Number(document.getElementById('updateWins').value || 0);
    const losses = Number(document.getElementById('updateLosses').value || 0);

    if (!name) {
        setStatus('Player name required for update.', true);
        return;
    }

    try {
        const res = await fetch("/update_player", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ name, wins, losses })
        });

        if (!res.ok) {
            const errorData = await res.json();
            throw new Error(errorData.error || `Server returned status ${res.status}`);
        }

        const updatedPlayer = await res.json();
        
        // Refresh the entire list to show the new standings/rating
        await fetchPlayers(); 
        
        setStatus(`Updated records for '${updatedPlayer.name}'. New rating: ${updatedPlayer.rating.toFixed(0)}`);
    } catch (err) {
        console.error(err);
        setStatus('Failed to update player: ' + err.message, true);
    }

    // Clear inputs
    document.getElementById('updateName').value = '';
    document.getElementById('updateWins').value = '';
    document.getElementById('updateLosses').value = '';
}

// --- New Event Listener (at the end of script.js) ---
document.getElementById('updatePlayerBtn').addEventListener('click', updatePlayer);

// --- Remove Player Function ---
async function removePlayer() {
    const name = document.getElementById('removeName').value.trim();

    if (!name) {
        setStatus('Player name required for removal.', true);
        return;
    }

    if (!confirm(`Are you sure you want to remove '${name}' from the leaderboard?`)) {
        return;
    }

    try {
        const res = await fetch("/remove_player", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ name })
        });

        if (!res.ok) {
            const errorData = await res.json();
            throw new Error(errorData.error || `Server returned status ${res.status}`);
        }

        // Refresh the leaderboard to reflect the removal
        await fetchPlayers();

        setStatus(`Successfully removed '${name}' from the leaderboard.`);
    } catch (err) {
        console.error(err);
        setStatus('Failed to remove player: ' + err.message, true);
    }

    // Clear input
    document.getElementById('removeName').value = '';
}

// --- Event Listener for Remove Player ---
document.getElementById('removePlayerBtn').addEventListener('click', removePlayer);

// initial load
fetchPlayers();